version: '3'
services:
  web:
    image: devsproci/iot_controller:1
    command: bash -c
            ' rm ./tmp/pids/server.pid
            & bundle exec rails s -p 3000 -b "0.0.0.0"'
    volumes:
      - .:/iot_controller
    ports:
      - 3000:3000
    depends_on:
      - neo4j_dev
      - neo4j_test
    tty: true
    stdin_open: true

  neo4j_dev:
    image: neo4j:3.5.9
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/test
    volumes:
      - neo4j_dev_data:/data

  neo4j_test:
    image: neo4j:3.5.9
    ports:
      - 3001:7474
      - 3002:3002
    environment:
      - NEO4J_AUTH=neo4j/test
      - NEO4J_dbms_connector_bolt_listen__address=:3002
    volumes:
      - neo4j_test_data:/data

  redis:
    image: redis
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  sidekiq:
    tty: true
    stdin_open: true
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - .:/iot_controller
    depends_on:
      - redis

volumes:
  redis_data:
    driver: local
  neo4j_dev_data:
    driver: local
  neo4j_test_data:
    driver: local
