version: '3'
services:
  proxy:
    image: jwilder/nginx-proxy:latest
    container_name: iot_proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro

  web:
    image: zonawiki/iot_controller:prod
    build:
      context: .
      dockerfile: ./docker/prod/Dockerfile
    environment:
      - VIRTUAL_HOST=ec2-34-239-60-25.compute-1.amazonaws.com
      - RAILS_ENV=production
      - NEO4J_TYPE=https
      #- NEO4J_URL=https://neo4j:neoproci@18.214.125.46:7473
    volumes:
      - /var/www/iot_controller/shared/config/application.yml:/iot_controller/config/application.yml
      - /var/www/iot_controller/shared/config/database.yml:/iot_controller/config/database.yml
      - /var/www/iot_controller/shared/config/neo4j.yml:/iot_controller/config/neo4j.yml
      - /var/www/iot_controller/shared/config/secrets.yml:/iot_controller/config/secrets.yml

  redis:
    image: redis
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  sidekiq:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: ./docker/prod/Dockerfile
    environment:
      - RAILS_ENV=production
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - /var/www/iot_controller/shared/config/application.yml:/iot_controller/config/application.yml
      - /var/www/iot_controller/shared/config/database.yml:/iot_controller/config/database.yml
      - /var/www/iot_controller/shared/config/neo4j.yml:/iot_controller/config/neo4j.yml
      - /var/www/iot_controller/shared/config/secrets.yml:/iot_controller/config/secrets.yml
    depends_on:
      - redis

volumes:
  redis_data:
    driver: local
