version: '3'
services:
  web:
    image: zonawik1/iot_controller:1
    command: bash -c 'bin/webpack --watch --progress --color & bundle exec rails s -p 3000 -b "0.0.0.0"'
    volumes:
      - .:/iot_controller
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
